function [var] = getvar(dataSource)
    if(strcmp(dataSource,'vcg'))
        % VCG set of variables
        var = {'second',...
            'VCU_HVACVlvA','VCU_HVACVlvB','VCU_HVACVlvF','VCU_HVACVlvG','VCU_HVACVlvE',...
            'VCU_HVACClntPump1','VCU_HVACClntPump2',...
            'VCU_HVACClngSysMd','VCU_ClntPmp1PWM','VCU_HVACClntPmp2PWM','VCU_HVACVlvD','BMS_IntTemp',...
            'HUD_Odmr','HUD_VehSpd',...
            'Invr_MtrTemp', 'Invr_OilPres','Invr_OilTemp',...
            'Invr_CtrlBrdTemp','Invr_ModA_Temp','Invr_GateDrvrBrd', 'DCDC_Temp',...
            'VCU_HVACIRHtr',...
            'VCU_HVACSATemp','VCU_HVACSBTemp','VCU_HVACSDTemp','VCU_HVACSETemp','VCU_HVACCbnTemp','VCU_HVACSCTemp','VCU_HVACAmbtTemp',...
            'VCU_HVACClntMtrFlwSw','VCU_HVACIRHtrFlowSw',...
            'VCU_HVBtMod1Temp1','VCU_HVBtMod1Temp2','VCU_HVBtMod2Temp1','VCU_HVBtMod2Temp2','VCU_HVBtMod3Temp1','VCU_HVBtMod3Temp2','VCU_HVBtMod4Temp1','VCU_HVBtMod4Temp2',...
            'VCU_HVBtMod5Temp1','VCU_HVBtMod5Temp2','VCU_HVBtMod6Temp1','VCU_HVBtMod6Temp2','VCU_HVBtMod7Temp1','VCU_HVBtMod7Temp2','VCU_HVBtMod8Temp1','VCU_HVBtMod8Temp2',...
            'VCU_HVBtMod9Temp1','VCU_HVBtMod9Temp2',...
            'BMS_AvgTemp','BMS_HiTemp',...
            'HUD_SOC','BMS_PackSOC',...   
            'datetime (UTC)','HUD_HVBtTemp',...
            'BMS_LoTemp','VCU_HVACAC','VCU_HVACFan1','VCU_HVACFan2','OBC_Temp',...
            'Invr_ModBTemp','Invr_ModCTemp',...
            'Invr_PhseACurr','HUD_ActTrq','HUD_ReqTrq','HUD_MtrFdBkTrq'
             };  
    elseif(strcmp(dataSource,'raptor'))
        % Raptor Cal Set of Variable Names
        var = {'Timestamp (ms)',...
            'HVAC_VlvAOut (Bool)','HVAC_VlvBOut (Bool)','HVAC_VlvCOut (Bool)','HVAC_VlvDOut (Bool)','HVAC_VlvEOut (Bool)',...
            'HVAC_ClntPmp1Out (Bool)','HVAC_ClntPmp2Out (Bool)',...
            'HVAC_Md','HVAC_MdA','HVAC_MdB','HVAC_MdC','HVAC_RunMd',...
            'HUD_Odmr (miles)','HUD_VehSpd',...
            'Invr_MtrTemp (degC)','Invr_OilPres (Psi)','Invr_OilTemp (degC)',...
            'Invr_CtrlBrdTemp (degC)','Invr_ModA_Temp (degC)','Invr_GateDrvrBrd (degC)','DCDC_Temp (degC)',...
            'HVAC_IRHtrCttrOut (Bool)',...
            'HVAC_SATemp (deg C)','HVAC_SBTemp (deg C)','HVAC_SDTemp (deg C)','HVAC_SETemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_IRHtrInsdTemp (deg C)','HVAC_AmbTemp (deg C)',...
            'HVAC_MtrFlowSw (Bool)','HVAC_IRHtrFlowSw (Bool)',...
            'HVBt_Mod1Temp1','HVBt_Mod1Temp2','HVBt_Mod2Temp1','HVBt_Mod2Temp2','HVBt_Mod3Temp1','HVBt_Mod3Temp2','HVBt_Mod4Temp1','HVBt_Mod4Temp2',...
            'HVBt_Mod5Temp1','HVBt_Mod5Temp2','HVBt_Mod6Temp1','HVBt_Mod6Temp2','HVBt_Mod7Temp1','HVBt_Mod7Temp2','HVBt_Mod8Temp1','HVBt_Mod8Temp2',...
            'HVBt_Mod9Temp1','HVBt_Mod9Temp2',...
            'BMS_AvgTemp (Celsius)','BMS_HiTemp (Celsius)',...
            'HUD_SOC','BMS_PackSOC (Percent)',...
            'Invr_ModBTemp (degC)','Invr_ModCTemp (degC)',...
            'HV_PTC_HV_DC_Curr (amps)','HV_PTC_HeatReq (%)','HV_PTC_On_Rq (Index)',...
            'HUD_HvBtVltg','HVH_Current_Consumption (Units)'
             };
    elseif(strcmp(dataSource,'vcg_fleetManager')) 
        % VCG set of variables from Fleet Manager
        var = {'second',...
            'VCU_HVACVlvA','VCU_HVACVlvB','VCU_HVACVlvF','VCU_HVACVlvG','VCU_HVACVlvE',...
            'VCU_HVACClntPump1','VCU_HVACClntPump2',...
            'VCU_HVACClngSysMd_ver2','VCU_ClntPmp1PWM','VCU_HVACClntPmp2PWM','VCU_HVACVlvD','BMS_IntTemp',...
            'Odometer','Speed',...
            'Invr_MtrTemp', 'Invr_OilPres','Invr_OilTemp',...
            'Invr_CtrlBrdTemp','Invr_ModA_Temp','Invr_GateDrvrBrd', 'DCDC_Temp',...
            'VCU_HVACIRHtr',...
            'VCU_HVACSATemp','VCU_HVACSBTemp','VCU_HVACSDTemp','VCU_HVACSETemp','VCU_HVACCbnTemp','VCU_HVACSCTemp','VCU_HVACAmbtTemp',...
            'VCU_HVACClntMtrFlwSw','VCU_HVACIRHtrFlowSw',...
            'VCU_HVBtMod1Temp1','VCU_HVBtMod1Temp2','VCU_HVBtMod2Temp1','VCU_HVBtMod2Temp2','VCU_HVBtMod3Temp1','VCU_HVBtMod3Temp2','VCU_HVBtMod4Temp1','VCU_HVBtMod4Temp2',...
            'VCU_HVBtMod5Temp1','VCU_HVBtMod5Temp2','VCU_HVBtMod6Temp1','VCU_HVBtMod6Temp2','VCU_HVBtMod7Temp1','VCU_HVBtMod7Temp2','VCU_HVBtMod8Temp1','VCU_HVBtMod8Temp2',...
            'VCU_HVBtMod9Temp1','VCU_HVBtMod9Temp2',...
            'Average_Temp','BMS_HiTemp',...
            'State_of_Charge','BMS_PackSOC',...   
            'HUD_HVBtTemp','HUD_HVBtTemp',...
            'BMS_LoTemp','VCU_HVACAC','VCU_HVACFan1','VCU_HVACFan2','OBC_Temp',...
            'Invr_ModBTemp','Invr_ModCTemp',...
            'Invr_PhseACurr',...
            'VCU_FlngFlt1Indx','VCU_FlngFlt2Indx','VCU_FlngFlt3Indx','VCU_FlngFlt4Indx','VCU_FlngFlt5Indx','VCU_FlngFlt6Indx'
            };      
    elseif(strcmp(dataSource,'raptor_brightview')) 
        % VCG set of variables from Fleet Manager
        var = {'Timestamp (ms)',...
            'Flt049_HVAC_VlvAOut (Bool)','Flt050_HVAC_VlvBOut (Bool)','Flt051_HVAC_VlvCOut (Bool)','Flt052_HVAC_VlvDOut (Bool)','Flt053_HVAC_VlvEOut (Bool)',...
            'Flt041_HVAC_ClntPmp1Out (Bool)','Flt042_HVAC_ClntPmp2Out (Bool)',...
            'HVAC_MdReq','HVAC_MdReq','HVAC_MdReq','HVAC_MdReq','HVAC_MdReq',...
            'HUD_Odmr (miles)','HUD_VehSpd',...
            'Invr_MtrTemp (degC)','Invr_OilPres (Psi)','Invr_OilTemp (degC)',...
            'Invr_CtrlBrdTemp (degC)','Invr_ModA_Temp (degC)','Invr_GateDrvrBrd (degC)','DCDC_Temp (degC)',...
            'DCDC_Temp (degC)',...
            'HVAC_SATemp (deg C)','HVAC_SBTemp (deg C)','HVAC_SCTemp (deg C)','HVAC_SGTemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_AmbTemp (deg C)',...
            'HVAC_FlwSw1 (Bool)','HVAC_FlwSw3 (Bool)',...
            'HVBt_Mod1Temp1','HVBt_Mod1Temp2','HVBt_Mod2Temp1','HVBt_Mod2Temp2','HVBt_Mod3Temp1','HVBt_Mod3Temp2','HVBt_Mod4Temp1','HVBt_Mod4Temp2',...
            'HVBt_Mod5Temp1','HVBt_Mod5Temp2','HVBt_Mod6Temp1','HVBt2_Mod6Temp2','HVBt_Mod7Temp1','HVBt_Mod7Temp2','HVBt_Mod8Temp1','HVBt_Mod8Temp2',...
            'HVBt_Mod9Temp1','HVBt_Mod9Temp2',...
            'HUD_SOC','HUD_SOC',...
            'HUD_SOC','HUD_SOC',...
            'Invr_ModBTemp (degC)','Invr_ModCTemp (degC)',...
            'HVH_Current_Consumption (Units)','HVH_Current_Consumption (Units)','HVH_Current_Consumption (Units)',...
            'HUD_HvBtVltg','HVH_Current_Consumption (Units)', 'Flt183_HVAC_ClntPmp3Out (Bool)',...
            'HVBt2_Mod1Temp1','HVBt2_Mod1Temp2','HVBt2_Mod2Temp1','HVBt2_Mod2Temp2','HVBt2_Mod3Temp1','HVBt2_Mod3Temp2','HVBt2_Mod4Temp1','HVBt2_Mod4Temp2',...
            'HVBt2_Mod5Temp1','HVBt2_Mod5Temp2','HVBt2_Mod6Temp1','HVBt2_Mod6Temp2','HVBt2_Mod7Temp1','HVBt2_Mod7Temp2','HVBt2_Mod8Temp1','HVBt2_Mod8Temp2',...
            'HVBt2_Mod9Temp1','HVBt2_Mod9Temp2',...
            'HVAC_ClntFlwMd','HVAC_RfgFlwMd','HVAC_FanMd','HVAC_HeatMd','HVAC_InvrTempMd','HVAC_HVBtTempMd','HVAC_FanTempMd'...
            'HVAC_SDTemp (deg C)','HVAC_SETemp (deg C)','HVAC_SFTemp (deg C)','HVAC_SHTemp (deg C)','HVAC_SITemp (deg C)',...
            'Flt043_HVAC_Fan1Out (Bool)','Flt044_HVAC_Fan2Out (Bool)','HVAC_ACSpdReqFnl (rpm)','HVAC_ACPres (psi)',...
            'HVH_HeaterEnable (boolean)','Invr_MtrSpd (rpm)','HUD_HVBtCurr (AMPS)','HUD_HVBtPwr (KW)',...
            'HVAC_ACEnable','HVAC_BlwrEnbl','VCU_HVACBlwr (Index)','VCU_HVACAC (Index)','VCU_Dfst (Index)','HVAC_HeatReq (Bool)','HVAC_HeatEnbl',...
            'HVAC_FlwSw2 (Bool)'            
            };        
        
    elseif(strcmp(dataSource,'vcg_fleetManager_brightview')) 
        % VCG set of variables from Fleet Manager
        var = {'Timestamp (ms)',...
            'Flt049_HVAC_VlvAOut (Bool)','Flt050_HVAC_VlvBOut (Bool)','Flt051_HVAC_VlvCOut (Bool)','Flt052_HVAC_VlvDOut (Bool)','Flt053_HVAC_VlvEOut (Bool)',...
            'Flt041_HVAC_ClntPmp1Out (Bool)','Flt042_HVAC_ClntPmp2Out (Bool)',...vl
            'HVAC_MdReq','HVAC_MdReq','HVAC_MdReq','HVAC_MdReq','HVAC_MdReq',...
            'HUD_Odmr (miles)','HUD_VehSpd',...
            'Invr_MtrTemp (degC)','Invr_OilPres (Psi)','Invr_OilTemp (degC)',...
            'Invr_CtrlBrdTemp (degC)','Invr_ModA_Temp (degC)','Invr_GateDrvrBrd (degC)','DCDC_Temp (degC)',...
            'DCDC_Temp (degC)',...
            'HVAC_SATemp (deg C)','HVAC_SBTemp (deg C)','HVAC_SCTemp (deg C)','HVAC_SGTemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_AmbTemp (deg C)',...
            'HVAC_FlwSw1 (Bool)','HVAC_FlwSw3 (Bool)',...
            'HVBt_Mod1Temp1','HVBt_Mod1Temp2','HVBt_Mod2Temp1','HVBt_Mod2Temp2','HVBt_Mod3Temp1','HVBt_Mod3Temp2','HVBt_Mod4Temp1','HVBt_Mod4Temp2',...
            'HVBt_Mod5Temp1','HVBt_Mod5Temp2','HVBt_Mod6Temp1','HVBt2_Mod6Temp2','HVBt_Mod7Temp1','HVBt_Mod7Temp2','HVBt_Mod8Temp1','HVBt_Mod8Temp2',...
            'HVBt_Mod9Temp1','HVBt_Mod9Temp2',...
            'HUD_SOC','HUD_SOC',...
            'HUD_SOC','HUD_SOC',...
            'Invr_ModBTemp (degC)','Invr_ModCTemp (degC)',...
            'VCU_HVHElecCurr','VCU_HVHElecCurr','VCU_HVHElecCurr',...
            'HUD_HvBtVltg','VCU_HVHElecCurr', 'VCU_HVHElecCurr',...
            'HVBt2_Mod1Temp1','HVBt2_Mod1Temp2','HVBt2_Mod2Temp1','HVBt2_Mod2Temp2','HVBt2_Mod3Temp1','HVBt2_Mod3Temp2','HVBt2_Mod4Temp1','HVBt2_Mod4Temp2',...
            'HVBt2_Mod5Temp1','HVBt2_Mod5Temp2','HVBt2_Mod6Temp1','HVBt2_Mod6Temp2','HVBt2_Mod7Temp1','HVBt2_Mod7Temp2','HVBt2_Mod8Temp1','HVBt2_Mod8Temp2',...
            'HVBt2_Mod9Temp1','HVBt2_Mod9Temp2',...
            'HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)'...
            'HVAC_SDTemp (deg C)','HVAC_SETemp (deg C)','HVAC_SFTemp (deg C)','HVAC_SHTemp (deg C)','HVAC_SITemp (deg C)',...
            'VCU_HVACFan1','VCU_HVACFan2','HVAC_ACSpd','HVAC_ACSpdReq',...
            'VCU_HVHActPwr','Invr_MtrSpd','HUD_HVBtCurr','HUD_HVBtPwr (KW)',...
            'HVAC_ACEnable','HVAC_BlwrEnbl','VCU_HVACBlwr (Index)','VCU_HVACAC (Index)','VCU_Dfst (Index)','HVAC_HeatReq (Bool)','HVAC_HeatEnbl',...
            'HVAC_FlwSw2 (Bool)'            
            };

    elseif(strcmp(dataSource,'vcg_fleetManager_breezeline')) % see if this can actually be v5.1 Test Dual ZEUS config instead of being specific to that one vehicle
        % VCG set of variables from Fleet Manager
        var = {'Timestamp (ms)',...
            'Flt049_HVAC_VlvAOut (Bool)','Flt050_HVAC_VlvBOut (Bool)','Flt051_HVAC_VlvCOut (Bool)','Flt052_HVAC_VlvDOut (Bool)','Flt053_HVAC_VlvEOut (Bool)',...
            'Flt041_HVAC_ClntPmp1Out (Bool)','Flt042_HVAC_ClntPmp2Out (Bool)',...vl
            'HVAC_MdReq','HVAC_MdReq','HVAC_MdReq','HVAC_MdReq','HVAC_MdReq',...
            'HUD_Odmr (miles)','HUD_VehSpd',...
            'Invr_MtrTemp (degC)','Invr_OilPres (Psi)','Invr_OilTemp (degC)',...
            'Invr_CtrlBrdTemp (degC)','Invr_ModA_Temp (degC)','Invr_GateDrvrBrd (degC)','DCDC_Temp (degC)',...
            'DCDC_Temp (degC)',...
            'HVAC_SATemp (deg C)','HVAC_SBTemp (deg C)','HVAC_SCTemp (deg C)','HVAC_SGTemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_CbnTemp (deg C)','HVAC_AmbTemp (deg C)',...
            'HVAC_FlwSw1 (Bool)','HVAC_FlwSw3 (Bool)',...
            'HVBt_Mod1Temp1','HVBt_Mod1Temp2','HVBt_Mod2Temp1','HVBt_Mod2Temp2','HVBt_Mod3Temp1','HVBt_Mod3Temp2','HVBt_Mod4Temp1','HVBt_Mod4Temp2',...
            'HVBt_Mod5Temp1','HVBt_Mod5Temp2','HVBt_Mod6Temp1','HVBt2_Mod6Temp2','HVBt_Mod7Temp1','HVBt_Mod7Temp2','HVBt_Mod8Temp1','HVBt_Mod8Temp2',...
            'HVBt_Mod9Temp1','HVBt_Mod9Temp2',...
            'HUD_SOC','HUD_SOC',...
            'HUD_SOC','HUD_SOC',...
            'Invr_ModBTemp (degC)','Invr_ModCTemp (degC)',...
            'VCU_HVHElecCurr','VCU_HVHElecCurr','VCU_HVHElecCurr',...
            'HUD_HvBtVltg','VCU_HVHElecCurr', 'VCU_HVHElecCurr',...
            'HVBt2_Mod1Temp1','HVBt2_Mod1Temp2','HVBt2_Mod2Temp1','HVBt2_Mod2Temp2','HVBt2_Mod3Temp1','HVBt2_Mod3Temp2','HVBt2_Mod4Temp1','HVBt2_Mod4Temp2',...
            'HVBt2_Mod5Temp1','HVBt2_Mod5Temp2','HVBt2_Mod6Temp1','HVBt2_Mod6Temp2','HVBt2_Mod7Temp1','HVBt2_Mod7Temp2','HVBt2_Mod8Temp1','HVBt2_Mod8Temp2',...
            'HVBt2_Mod9Temp1','HVBt2_Mod9Temp2',...
            'HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)','HUD_Odmr (miles)'...
            'HVAC_SDTemp (deg C)','HVAC_SETemp (deg C)','HVAC_SFTemp (deg C)','HVAC_SHTemp (deg C)','HVAC_SITemp (deg C)',...
            'VCU_HVACFan1','VCU_HVACFan2','HVAC_ACSpd','HVAC_ACSpdReq',...
            'VCU_HVHActPwr','Invr_MtrSpd','HUD_HVBtCurr','HUD_HVBtPwr (KW)',...
            'HVAC_ACEnable','HVAC_BlwrEnbl','VCU_HVACBlwr (Index)','VCU_HVACAC (Index)','VCU_Dfst (Index)','HVAC_HeatReq (Bool)','HVAC_HeatEnbl',...
            'HVAC_FlwSw2 (Bool)'            
            };
    elseif(strcmp(dataSource,'raptor_v5_1')) 
        % VCG set of variables from Fleet Manager
        var = {'Timestamp (ms)',...
            'HUD_Odmr (miles)','HUD_VehSpd',...
            'HVAC_MdMsmt','HVAC_Md','HVAC_Md_OvrSts','HVAC_Md_OvrVal','HVAC_MdReq',...                              % mode stuff
            'Invr_MtrTemp (degC)','Invr_OilTemp (degC)','Invr_OilPres (Psi)','Invr_MtrSpd (rpm)',...                % motor stuff
            'Invr_CtrlBrdTemp (degC)','Invr_ModA_Temp (degC)','Invr_ModBTemp (degC)','Invr_ModCTemp (degC)','Invr_GateDrvrBrd (degC)',...                         % invr stuff
            'DCDC_Temp (degC)','OBC_Temp (degC)',...
            'HVBt_Mod1Temp1 (deg C)','HVBt_Mod1Temp2 (deg C)','HVBt_Mod2Temp1 (deg C)','HVBt_Mod2Temp2 (deg C)','HVBt_Mod3Temp1 (deg C)','HVBt_Mod3Temp2 (deg C)','HVBt_Mod4Temp1 (deg C)','HVBt_Mod4Temp2 (deg C)',...
            'HVBt_Mod5Temp1 (deg C)','HVBt_Mod5Temp2 (deg C)','HVBt_Mod6Temp1 (deg C)','HVBt_Mod6Temp2 (deg C)','HVBt_Mod7Temp1 (deg C)','HVBt_Mod7Temp2 (deg C)','HVBt_Mod8Temp1 (deg C)','HVBt_Mod8Temp2 (deg C)',...
            'HVBt_Mod9Temp1 (deg C)','HVBt_Mod9Temp2 (deg C)',...
            'HVAC_CTBI (deg C)','HVAC_CTDI (deg C)','HVAC_CTCO (deg C)','HVAC_CTHCI (deg C)','HVAC_CTRHCI (deg C)',...
            'HVAC_SATemp (deg C)','HVAC_SBTemp (deg C)','HVAC_SCTemp (deg C)','HVAC_SDTemp (deg C)','HVAC_SETemp (deg C)','HVAC_SFTemp (deg C)','HVAC_SGTemp (deg C)','HVAC_SHTemp (deg C)',...
            'HVAC_CbnTemp (deg C)','HVAC_AmbTemp (deg C)',...
            'HVAC_ClntFlwMdMeas','HVAC_RfgFlwMdMeas','HVAC_FanMdMeas','HVAC_HeatMdMeas','HVAC_InvrTempMd','HVAC_HVBtTempMd','HVAC_FanTempMd'...
            'Flt049_HVAC_VlvAOut (Bool)','Flt050_HVAC_VlvBOut (Bool)','Flt051_HVAC_VlvCOut (Bool)','Flt052_HVAC_VlvDOut (Bool)','Flt053_HVAC_VlvEOut (Bool)',...
            'Flt041_HVAC_ClntPmp1Out (Bool)','Flt042_HVAC_ClntPmp2Out (Bool)','Flt183_HVAC_ClntPmp3Out (Bool)',...
            'HVAC_InvrFlowSw (Bool)','HVAC_HVHHtrFlowSw (Bool)','HVAC_FlwSw2 (Bool)',...
            'HUD_SOC','HUD_HvBtVltg',...
            'Flt043_HVAC_Fan1Out (Bool)','Flt044_HVAC_Fan2Out (Bool)',...
            'HV_PTC_On_Rq (Index)','HUD_HVBtCurr (AMPS)','HUD_HVBtPwr (KW)',...
            'HVAC_ACSpdReqFnl (rpm)','HVAC_ACPres (psi)',...          
            };
     elseif(strcmp(dataSource,'raptor_CAFU')) 
        % raptor dataset from CAFU
        var = {
            'Timestamp (ms)',...
            'TMS_HVBtFanMd','TMS_HVBtTMSMdMes','TMS_ELTMSMdMes',... % the first item will be TMSMd
            ... % pack1 temps
            'HVBt_Mod1Temp1','HVBt_Mod1Temp2','HVBt_Mod2Temp1','HVBt_Mod2Temp2','HVBt_Mod3Temp1','HVBt_Mod3Temp2','HVBt_Mod4Temp1','HVBt_Mod4Temp2',...
            'HVBt_Mod5Temp1','HVBt_Mod5Temp2','HVBt_Mod6Temp1','HVBt_Mod6Temp2','HVBt_Mod7Temp1','HVBt_Mod7Temp2','HVBt_Mod8Temp1','HVBt_Mod8Temp2',...
            'HVBt_Mod9Temp1','HVBt_Mod9Temp2',...
            ... %pack2 temps
            'HVBt2_Mod1Temp1','HVBt2_Mod1Temp2','HVBt2_Mod2Temp1','HVBt2_Mod2Temp2','HVBt2_Mod3Temp1','HVBt2_Mod3Temp2','HVBt2_Mod4Temp1','HVBt2_Mod4Temp2',...
            'HVBt2_Mod5Temp1','HVBt2_Mod5Temp2','HVBt2_Mod6Temp1','HVBt2_Mod6Temp2','HVBt2_Mod7Temp1','HVBt2_Mod7Temp2','HVBt2_Mod8Temp1','HVBt2_Mod8Temp2',...
            'HVBt2_Mod9Temp1','HVBt2_Mod9Temp2',...
            ... %pack3 temps
            'HVBt3_Mod1Temp1','HVBt3_Mod1Temp2','HVBt3_Mod2Temp1','HVBt3_Mod2Temp2','HVBt3_Mod3Temp1','HVBt3_Mod3Temp2','HVBt3_Mod4Temp1','HVBt3_Mod4Temp2',...
            'HVBt3_Mod5Temp1','HVBt3_Mod5Temp2','HVBt3_Mod6Temp1','HVBt3_Mod6Temp2','HVBt3_Mod7Temp1','HVBt3_Mod7Temp2','HVBt3_Mod8Temp1','HVBt3_Mod8Temp2',...
            'HVBt3_Mod9Temp1','HVBt3_Mod9Temp2',...
            ... %pack4 temps
            'HVBt4_Mod1Temp1','HVBt4_Mod1Temp2','HVBt4_Mod2Temp1','HVBt4_Mod2Temp2','HVBt4_Mod3Temp1','HVBt4_Mod3Temp2','HVBt4_Mod4Temp1','HVBt4_Mod4Temp2',...
            'HVBt4_Mod5Temp1','HVBt4_Mod5Temp2','HVBt4_Mod6Temp1','HVBt4_Mod6Temp2','HVBt4_Mod7Temp1','HVBt4_Mod7Temp2','HVBt4_Mod8Temp1','HVBt4_Mod8Temp2',...
            'HVBt4_Mod9Temp1','HVBt4_Mod9Temp2',...
            'TMS_CTBI','TMS_CTDI','TMS_CTBBI','TMS_CTBB2I','TMS_CTBB4I',...% coolant temps
            'TMS_D1','TMS_D2','TMS_D3',...test coolant temps
            'TMS_HVBtFansTemp','TMS_ELFansTemp','TMS_VentTemp',... % air temps
            ... % BB coolant Temps
            'Rpt_Temp_waterout1','Rpt_Temp_waterin1','Rpt_Temp_waterout2','Rpt_Temp_waterin2','Rpt_Temp_waterout3','Rpt_Temp_waterin3','Rpt_Temp_waterout4','Rpt_Temp_waterin4',...
            ... % BB & DCDC/OBC Component Temps
            'Report_DCTemp1','Report_DCTemp2','Report_DCTemp3','Report_DCTemp4','DCDC_Temp (degC)','OBC_Temp (degC)',...
            ... % Comp Enbl
            'TMS_HVBtCompEnbl','TMS_ELCompEnbl',...
            ... % Compressors' Spd
            'TMS_HVBtCompSpdReqMeas (rpm)','TMS_HVBtCompSpdReqFnl (rpm)','TMS_HVBtCompSpdReq_Output (rpm)',...
            'TMS_ELCompSpdReqMeas (rpm)','TMS_ELCompSpdReq_Output (rpm)','TMS_ELCompSpdReqFnl (rpm)'...
            ... % compressors' pressures
            'TMS_HVBtComp_RefgLowSidePres (psi)','TMS_HVBtComp_RefgHighSidePres (psi)','TMS_HVBtComp_RefgLowSidePresADC (ADC)','TMS_HVBtComp_RefgHighSidePresADC (ADC)','TMS_HVBtComp_RefgLowSidePres_OvrVal (psi)','TMS_HVBtComp_RefgHighSidePres_OvrVal (psi)',...
            'TMS_ELComp_RefgLowSidePres (psi)','TMS_ELComp_RefgHighSidePres (psi)','TMS_ELComp_RefgLowSidePresADC (ADC)','TMS_ELComp_RefgHighSidePresADC (ADC)','TMS_ELComp_RefgLowSidePres_OvrVal (psi)','TMS_ELComp_RefgHighSidePres_OvrVal (psi)'...
            ... % CCS parameters
            'CCS1_targetCurrent (A)','CCS1_drivenCurrent (A)','CCS1_measuredCurrent (A)',...
            'CCS1_targetVoltage (V)','CCS1_drivenVoltage (V)','CCS1_measuredVoltage (V)',...
            'CCS2_targetCurrent (A)','CCS2_drivenCurrent (A)','CCS2_measuredCurrent (A)',...
            'CCS2_targetVoltage (V)','CCS2_drivenVoltage (V)','CCS2_measuredVoltage (V)',...
            ... % Fans Enbl
            'TMS_HVBtFansEnbl','TMS_ELFanEnbl',...
            ... % Input Temp Modes
            'TMS_HVBtTempMd','TMS_DcdcObcTempMd','TMS_BB34TempMd','TMS_BB12TempMd','TMS_HVBtFanTempMd','TMS_ELFanTempMd',...
            ... % system 
            'HVSys_StrtUpShtDwnStep','HUD_HVBtCurr (AMPS)','HUD_SOC',...
            ... % BB enbl req
            'BuckBoost_HVDCDC1_EnblReq','BuckBoost_HVDCDC2_EnblReq',...
            ... % TMS Meta
            'TMS_BldNo','TMS_Ver',...
            ... % TMS Md overrides
            'TMS_ELTMSMd_OvrVal','TMS_HVBtTMSMdOvrSet','TMS_ELTMSMdOvrSet',... % first one will be TMSMdoverride when that is available
            ... % Heater
            'HV_PTC_HV_DC_Curr (amps)','VCU_HVH2ElecCurr (Amps)',...
            'HV_PTC_InternalWaterTemp1 (degC)','HV_PTC_InternalWaterTemp2 (Units)',...
            'VCU_HVH2ClntInTemp (degC)','VCU_HVH2ClntOutTemp (degC)',...
            'Flt104_TMS_Htr1CntrOut (Bool)','Flt105_TMS_Htr2CntrOut (Bool)',...
            'TMS_HVBtHtr1Enbl','TMS_HVBtHtr2Enbl','VCU_HVH2Enbl (degC)',... 
            'BMS1_Pack_CCL (A)','BMS2_Pack_CCL (A)','BMS3_Pack_CCL (A)','BMS4_Pack_CCL (A)',...
            'EVCC_busbar_temperature_p (C)','EVCC_fcjb_temperature (C)','EVCC_busbar_temperature_n (C)',...
            'CompSpdReq_OvrVal (rpm)','CompSpdReq_Rear_OvrVal (rpm)',...
            'TMS_HVBtComp_RefgPresFlt','TMS_HVBtComp_RefgPresFlt_OvrVal','TMS_HVBtComp_RefgPresFlagHigh','TMS_HVBtComp_RefgPresFlagLow','TMS_HVBtComp_RefgPresFlagStatic',...
            'TMS_ELComp_RefgPresFlt','TMS_ELComp_RefgPresFlt_OvrVal','TMS_ELComp_RefgPresFlagHigh','TMS_ELComp_RefgPresFlagLow','TMS_ELComp_RefgPresFlagStatic'
            };
    elseif(strcmp(dataSource,'portal_CAFU')) 
        % raptor dataset from CAFU
        var = {
            'second',...
            'VCU_TMSClngSysMd_ver2','TMS_VCU_HVBtTMSMdMes','TMS_VCU_ELTMSMdMes',...
            ... % pack1 temps
            'BMS1_Mod1_Temp1','BMS1_Mod1_Temp2','BMS1_Mod2_Temp1','BMS1_Mod2_Temp2','BMS1_Mod3_Temp1','BMS1_Mod3_Temp2','BMS1_Mod4_Temp1','BMS1_Mod4_Temp2',...
            'BMS1_Mod5_Temp1','BMS1_Mod5_Temp2','BMS1_Mod6_Temp1','BMS1_Mod6_Temp2','BMS1_Mod7_Temp1','BMS1_Mod7_Temp2','BMS1_Mod8_Temp1','BMS1_Mod8_Temp2',...
            'BMS1_Mod9_Temp1','BMS1_Mod9_Temp2',...
            ... % pack2 temps
            'BMS2_Mod1_Temp1','BMS2_Mod1_Temp2','BMS2_Mod2_Temp1','BMS2_Mod2_Temp2','BMS2_Mod3_Temp1','BMS2_Mod3_Temp2','BMS2_Mod4_Temp1','BMS2_Mod4_Temp2',...
            'BMS2_Mod5_Temp1','BMS2_Mod5_Temp2','BMS2_Mod6_Temp1','BMS2_Mod6_Temp2','BMS2_Mod7_Temp1','BMS2_Mod7_Temp2','BMS2_Mod8_Temp1','BMS2_Mod8_Temp2',...
            'BMS2_Mod9_Temp1','BMS2_Mod9_Temp2',...
            ... % pack3 temps
            'BMS3_Mod1_Temp1','BMS3_Mod1_Temp2','BMS3_Mod2_Temp1','BMS3_Mod2_Temp2','BMS3_Mod3_Temp1','BMS3_Mod3_Temp2','BMS3_Mod4_Temp1','BMS3_Mod4_Temp2',...
            'BMS3_Mod5_Temp1','BMS3_Mod5_Temp2','BMS3_Mod6_Temp1','BMS3_Mod6_Temp2','BMS3_Mod7_Temp1','BMS3_Mod7_Temp2','BMS3_Mod8_Temp1','BMS3_Mod8_Temp2',...
            'BMS3_Mod9_Temp1','BMS3_Mod9_Temp2',...
            ... % pack4 temps
            'BMS4_Mod1_Temp1','BMS4_Mod1_Temp2','BMS4_Mod2_Temp1','BMS4_Mod2_Temp2','BMS4_Mod3_Temp1','BMS4_Mod3_Temp2','BMS4_Mod4_Temp1','BMS4_Mod4_Temp2',...
            'BMS4_Mod5_Temp1','BMS4_Mod5_Temp2','BMS4_Mod6_Temp1','BMS4_Mod6_Temp2','BMS4_Mod7_Temp1','BMS4_Mod7_Temp2','BMS4_Mod8_Temp1','BMS4_Mod8_Temp2',...
            'BMS4_Mod9_Temp1','BMS4_Mod9_Temp2',...
            ... % coolant temps - CTBI, CTDI, CTBBI, CTBB2I, CTBB4I
            'BMS1_Aux_Temp1','BMS1_Aux_Temp2','BMS1_Aux_Temp7','BMS1_Aux_Temp3','BMS1_Aux_Temp4',...            
            ... % test coolant temps
            'VCU_TMSD1Temp','VCU_TMSD2Temp','VCU_TMSD3Temp',...
            ... % air temps - HVBtFanTemp, ELFansTemp, VentTemp
            'BMS1_Aux_Temp6','BMS1_Aux_Temp5','BMS2_Aux_Temp4',...
            ... % BB coolant Temps
            'Rpt_Temp_waterout1','Rpt_Temp_waterin1','Rpt_Temp_waterout2','Rpt_Temp_waterin2','Rpt_Temp_waterout3','Rpt_Temp_waterin3','Rpt_Temp_waterout4','Rpt_Temp_waterin4',...
            ... % BB & DCDC/OBC Component Temps
            'Report_DCTemp1','Report_DCTemp2','Report_DCTemp3','Report_DCTemp4','DCDC_Temp','OBC_Temp', ...
            ... % Comp Enbl
            'VCU_TMSAC','TMS_VCU_ELCompEnbl',...
            ... % Compressors' Spd
            'TMS_VCU_TMS_HVBtCompSpdReqMeas','TMS_VCU_HVBtCompSpdReqFnl','TMS_VCU_HVBtCompSpdReq_Out',...
            'TMS_VCU_TMS_ELCompSpdReqMeas','TMS_VCU_ELCompSpdReqFnl','TMS_VCU_ELCompSpdReq_Out',...
            ... % compressors' pressures
            'TMS_VCU_HVBtComp_RefgLowSidePres','TMS_VCU_HVBtComp_RefgHighSidePres','','','','',...
            'TMS_VCU_ELComp_RefgLowSidePres','TMS_VCU_ELComp_RefgHighSidePres','','','','',...
            ... % CCS parameters
            'CCS1_targetCurrent','CCS1_drivenCurrent','CCS1_measuredCurrent',...
            'CCS1_targetVoltage','CCS1_drivenVoltage','CCS1_measuredVoltage',...
            'CCS2_targetCurrent','CCS2_drivenCurrent','CCS2_measuredCurrent',...
            'CCS2_targetVoltage','CCS2_drivenVoltage','CCS2_measuredVoltage',...
            ... % Fans Enbl
            'VCU_TMSFan1','VCU_TMSFan2',...
            ... % Input Temp Modes - HVBtTempMd missing at start
            '','TMS_VCU_DcdcObcTempMd','TMS_VCU_BB34TempMd','TMS_VCU_BB12TempMd','TMS_VCU_HVBtFanTempMd','TMS_VCU_ELFanTempMd',...
            ... % system 
            'VCU_HVStrtStep','HUD_HVBtCurr','State_of_Charge',...   
            ... % BB enbl req
            'Set_onoff1','Set_onoff2',...
            ... % TMS Meta - TMS BldNo and TMS Ver missing
            '','',...
            ... % TMS Md overrides - missing
            '','','',... % first one will be TMSMdoverride when that is available
            ... % Heater
            'VCU_HVHElecCurr','VCU_HVH2ElecCurr',...
            'Htr1_PTC_IntWaterTemp1','Htr1_PTC_IntWaterTemp2',...
            'VCU_HVH2ClntInTemp','VCU_HVH2ClntOutTemp',...
            'TMS_VCU_HVBtHtr1CntrOut','TMS_VCU_HVBtHtr2CntrOut',...
            'TMS_VCU_HVBtHtr1Enbl','TMS_VCU_HVBtHtr2Enbl','VCU_HVH2Enbl',... 
            'BMS1_Pack_CCL','BMS2_Pack_CCL','BMS3_Pack_CCL','BMS4_Pack_CCL',...
            'EVCC_busbar_temperature_p','EVCC_fcjb_temperature','EVCC_busbar_temperature_n'
            };
    end
end